# Generated by Django 4.2.16 on 2025-05-13 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='url')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='goods.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'db_table': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('sku', models.CharField(max_length=150, unique=True, verbose_name='Акртикул')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='url')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Скидка в %')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='goods.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'Product',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=150, unique=True, verbose_name='Акртикул вариации')),
                ('size', models.CharField(blank=True, choices=[('116-122', '116-122'), ('122-128', '122-128'), ('128-134', '128-134'), ('134-140', '134-140'), ('140-146', '140-146'), ('146-152', '146-152'), ('152-158', '152-158'), ('158-164', '158-164'), ('164-170', '164-170'), ('170-176', '170-176'), ('176-182', '176-182')], max_length=20, null=True)),
                ('producer_size', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='goods.products')),
            ],
            options={
                'verbose_name': 'Вариация',
                'verbose_name_plural': 'Вариации',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='good_images', verbose_name='Изображения вариаций')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.products')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Фотогалерея товаров',
            },
        ),
    ]
