# Generated by Django 4.2.16 on 2025-05-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='season',
            field=models.CharField(choices=[('spring_summer', 'Весна-Лето'), ('autumn_winter', 'Осень-Зима'), ('all_season', 'На любой сезон')], default='all_season', max_length=20, verbose_name='Сезонность'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='size',
            field=models.CharField(blank=True, choices=[('116-122', '116-122'), ('122-128', '122-128'), ('128-134', '128-134'), ('134-140', '134-140'), ('140-146', '140-146'), ('146-152', '146-152'), ('152-158', '152-158'), ('158-164', '158-164'), ('164-170', '164-170'), ('170-176', '170-176'), ('176-182', '176-182'), ('30 обувь', '30 обувь'), ('31 обувь', '31 обувь'), ('32 обувь', '32 обувь'), ('33 обувь', '33 обувь'), ('34 обувь', '34 обувь'), ('35 обувь', '35 обувь'), ('36 обувь', '36 обувь'), ('37 обувь', '37 обувь'), ('38 обувь', '38 обувь'), ('39 обувь', '39 обувь'), ('40 обувь', '40 обувь')], max_length=20, null=True),
        ),
    ]
