# Generated by Django 4.2.16 on 2025-05-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_products_season_alter_products_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'черный'), ('white', 'белый'), ('red', 'красный'), ('beige', 'бежевый'), ('khaki', 'хаки'), ('ping', 'розовый'), ('vio;', 'фиолетовый'), ('blue', 'синий'), ('green', 'зеленый'), ('yellow', 'желтый'), ('grey', 'серый'), ('brown', 'коричневый'), ('burgundy', 'бордовый')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='sku',
            field=models.CharField(max_length=150, unique=True, verbose_name='Артикул'),
        ),
    ]
