# Generated by Django 4.2.16 on 2025-05-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_total_price_orderitem_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Товар заказа', 'verbose_name_plural': 'Товары заказов'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В работе'), ('waiting_payment', 'Ожидает оплаты'), ('processing', 'Сборка'), ('shipped', 'Отправлен'), ('ended', 'Завершен'), ('cancelled', 'Отменён')], default='pending', max_length=20),
        ),
    ]
